export const colors = {
  string: `var(--string)`,
  variable: `var(--variable)`,
  property: `var(--property)`,
  number: `var(--number)`,
  operator: `var(--operator)`,
  punctuation: `var(--punctuation)`,
  comment: `var(--comment)`,
  function: `var(--function)`,
  keyword: `var(--keyword)`,
  attribute: `var(--attribute)`,
  class: `var(--class)`,
  tag: `var(--tag)`,
  error: `var(--error)`,
  border: `var(--border)`,
  linkColor: `var(--link-color)`,
  linkColorDarker: `var(--link-color-darker)`,
  linkHoverColor: `var(--link-hover-color)`,
  navBarColor: `var(--navbar-color)`,
  blockquote: `var(--blockquote)`,
  transpartentText: `var(--transparent-text)`,
  transparentBG: `var(--transparent-bg)`,
  lightTransparentGB: `var(--light-transparent-bg)`,
  borderColor: `var(--border-color)`,
  subtleBorder: `var(--subtle-border)`,
  font: {
    fontColor: `var(--font-color)`,
    headingColor: `var(--heading-color)`,
    darkFontColor: `var(--dark-font-color)`,
    mediumFontcolor: `var(--medium-font-color)`,
    lightFontColor: `var(--light-font-color)`,
  },
  background: {
    background: `var(--background)`,
    lightBackground: `var(--light-background)`,
    lightBackgroundHover: `var(--light-background-hover)`,
    codeBackgroundColor: `var(--code-background-color)`,
  },
} as const;

export const BasicColors = {
    "textLight": "#eee",
    "grey0": "#111",
    "grey1": "#191919",
    "grey2": "#2a2a2a",
    "grey3": "#494949",
    "grey4": "#616161",
    "grey5": "#8f8f8f",
    "blue0": "#55b2ff",
    "blue1": "#3099f0",
    "blue2": "#2d9efb",
    "blue3": "#1375c5",
    "danger0": "#f67070",
    "danger1": "#ff4d4d",
    "danger2": "#d13535",
    "success0": "#80e766",
    "success1": "#44a52c",
} as const